[package]
name = "json-rpc"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "^1", features = [ "derive" ] }
serde_json = { version = "^1", features = [ "raw_value" ] }
base64 = "^0.13.0"
